InitialCommit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -57,22 +57,37 @@ jobs:
      # Install OWASP Dependency-Check
       - name: Install OWASP Dependency-Check
         run: |
+          
           # Install unzip if not available
           sudo apt-get update
           sudo apt-get install -y unzip
+          
           # Download the OWASP Dependency-Check release
           wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.1/dependency-check-6.5.1-release.zip
+          
           # Verify the download
           if [ ! -f "dependency-check-6.5.1-release.zip" ]; then
             echo "Dependency-Check ZIP download failed!"
             exit 1
           fi
+
           # Unzip the downloaded file
           unzip dependency-check-6.5.1-release.zip -d /opt/
+          
           # Check the contents of the unzipped directory
           ls /opt/dependency-check*
+          
           # Create a symbolic link for easier access
           ln -s /opt/dependency-check/bin/dependency-check /usr/local/bin/dependency-check
+
+          # Check if the dependency-check executable is present
+          if [ ! -f "/opt/dependency-check/bin/dependency-check.sh" ]; then
+            echo "Dependency-Check executable not found!"
+            exit 1
+          fi
+
+          # Make the executable available in the PATH
+          sudo ln -s /opt/dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check
 
       # Run Dependency-Check for each app
       - name: Run Dependency-Check for ${{ matrix.app }}
